name: sample-test

on:
  pull_request:
    branches:
      - main

jobs:
  sample:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: sample
        run: echo "Hello"
